In [1]:
# MPAGE Package Testing
# This notebook demonstrates basic functionality of the MPAGE package

# Load the package
devtools::load_all()

ℹ Loading MPAGE




Warning message:
“Objects listed as exports, but not present in namespace:
• add_custom_proteins
• annotate_modules
• calculate_intra_pair_relationships
• calculate_inter_pair_relationships
• calculate_synergy_scores
• filter_ppi_network
• filter_rna_modules
• get_rna_mod_references
• identify_modules
• list_modification_types
• list_organisms
• load_modules
• load_ppi_network
• plot_pair_relationships
• save_modules
• save_ppi_network
• save_rna_mod_proteins
• validate_protein_file
• preprocess_intact_data
• load_intact_network
• download_intact_data”

In [2]:
modules <- readRDS("inst/extdata/rmp_modules.rds")
exp_data <- readRDS("data-raw/GSE26378_GPL570_gene_expression.rds")
pheno_data <- readRDS("data-raw/GSE26378_GPL570_phenotype.rds")

# names(modules) <- paste0("M_", 1:length(modules))
modules

$Module_1
$Module_1$module_id
[1] "RC4_1"

$Module_1$genes
 [1] "ALS2CR12"   "BAG4"       "C1QTNF2"    "DMRT2"      "FAM212A"
 [6] "FTO"        "GPANK1"     "IGLV2-11"   "MAGED1"     "OR1L3"
[11] "PBX4"       "SLC22A18AS" "SRGAP2B"    "TTC19"      "USP20"
[16] "TCIM"       "SMIM15"

$Module_1$size
[1] 17

$Module_1$algorithm
[1] "FASTGREEDY"

$Module_1$depth
[1] 4

$Module_1$target_proteins
[1] "FTO"


$Module_2
$Module_2$module_id
[1] "RC6_1"

$Module_2$genes
 [1] "ACAD10"   "CD226"    "DSTYK"    "HCST"     "KIAA1586" "KIR2DL4"
 [7] "KLRC2"    "KLRC4"    "KLRD1"    "MICB"     "NCR2"     "NCR3LG1"
[13] "NSUN3"    "SEC14L1"  "TMEM184B" "TMEM62"   "TMEM183A"

$Module_2$size
[1] 17

$Module_2$algorithm
[1] "FASTGREEDY"

$Module_2$depth
[1] 6

$Module_2$target_proteins
[1] "NSUN3"


$Module_3
$Module_3$module_id
[1] "RC4_1"

$Module_3$genes
 [1] "AARSD1"       "ALAD"         "ARHGAP8"      "ARPC1A"       "ARPP19"
 [6] "ARPP21"       "C14ORF142"    "DBNL"         "EFTUD1"       "ENSA"
[11] "GON7"         "KIAA1279"     "LPP"          "OSGEP"        "PANK4"
[16] "PPME1"        "PRR5-ARHGAP8" "RBBP9"        "RSC1A1"       "SAE1"
[21] "SEPT8"        "SH3GL1"       "SH3GL3"       "TP53RK"       "TPD52L2"
[26] "TPRKB"        "TRMT10A"      "UBA5"         "UFM1"         "WDR4"
[31] "YRDC"         "RNASE9"

$Module_3$size
[1] 32

$Module_3$algorithm
[1] "FASTGREEDY"

$Module_3$depth
[1] 4

$Module_3$target_proteins
[1] "WDR4"


$Module_4
$Module_4$module_id
[1] "RC5_1"

$Module_4$genes
 [1] "ASB3"        "ASB6"        "C16ORF89"    "CUL5"        "DCUN1D1"
 [6] "FAM120B"     "IGHV3OR15-7" "LANCL2"      "LRRC41"      "OSR1"
[11] "QPCT"        "RNMT"        "RPL7AP27"    "SPANXN4"     "VHL"
[16] "WSB1"        "RPL36AP37"   "RPL21P16"    "RPL21P19"    "RPL7AP9"
[21] "RPL7P32"     "RPS26P54"    "RPSAP12"     "TCEB1P3"

$Module_4$size
[1] 24

$Module_4$algorithm
[1] "FASTGREEDY"

$Module_4$depth
[1] 5

$Module_4$target_proteins
[1] "RNMT"


$Module_5
$Module_5$module_id
[1] "RC5_1"

$Module_5$genes
[1] "EEF1A1P5" "METTL3"   "UCHL1"

$Module_5$size
[1] 3

$Module_5$algorithm
[1] "FASTGREEDY"

$Module_5$depth
[1] 5

$Module_5$target_proteins
[1] "METTL3"


$Module_6
$Module_6$module_id
[1] "RC5_1"

$Module_6$genes
[1] "ALKBH3"  "CAPS"    "METTL22" "METTL23" "TPSB2"   "TUBB2A"  "TUBB4A"
[8] "ZC2HC1B" "VCPKMT"

$Module_6$size
[1] 9

$Module_6$algorithm
[1] "FASTGREEDY"

$Module_6$depth
[1] 5

$Module_6$target_proteins
[1] "ALKBH3"


$Module_7
$Module_7$module_id
[1] "RC3_1"

$Module_7$genes
[1] "FAM217A" "TET3"

$Module_7$size
[1] 2

$Module_7$algorithm
[1] "FASTGREEDY"

$Module_7$depth
[1] 3

$Module_7$target_proteins
[1] "TET3"


$Module_8
$Module_8$module_id
[1] "RC4_1"

$Module_8$genes
 [1] "DLEU1"     "DNMT3A"    "DNMT3B"    "EGLN1"     "EGLN2"     "H3-5"
 [7] "HIF3A"     "MPHOSPH8"  "NR6A1"     "SETDB1"    "ZNF10"     "ZNF274"
[13] "ZFP57"     "MIR124-3"  "LINC01270" "TRBV2"     "TASOR"

$Module_8$size
[1] 17

$Module_8$algorithm
[1] "FASTGREEDY"

$Module_8$depth
[1] 4

$Module_8$target_proteins
[1] "DNMT3A" "DNMT3B"


$Module_9
$Module_9$module_id
[1] "RC4_1"

$Module_9$genes
[1] "DNMT1"  "RELB"   "RNF180" "SNHG6"  "SNHG7"  "TOPORS" "ZNF263"

$Module_9$size
[1] 7

$Module_9$algorithm
[1] "FASTGREEDY"

$Module_9$depth
[1] 4

$Module_9$target_proteins
[1] "DNMT1"


$Module_10
$Module_10$module_id
[1] "RC5_1"

$Module_10$genes
 [1] "B9D2"      "DOK4"      "FOXP4-AS1" "KDM1A"     "KIAA1551"  "LIX1"
 [7] "PHF13"     "PHF21B"    "RARRES1"   "RBM20"     "RCOR1"     "RCOR3"
[13] "TET1"      "ZMYM4"     "ZNF318"    "ZSCAN5A"   "S100PBP"   "LINC00511"
[19] "SOX8"      "TSACC"

$Module_10$size
[1] 20

$Module_10$algorithm
[1] "FASTGREEDY"

$Module_10$depth
[1] 5

$Module_10$target_proteins
[1] "TET1"


$Module_11
$Module_11$module_id
[1] "RC5_1"

$Module_11$genes
 [1] "AR"     "BCOR"   "ERG"    "ETV5"   "FBRS"   "IQCK"   "KDM2B"  "KLF15"
 [9] "KLF5"   "NIPBL"  "SOX7"   "TET2"   "ZNF608" "ZNF609"

$Module_11$size
[1] 14

$Module_11$algorithm
[1] "FASTGREEDY"

$Module_11$depth
[1] 5

$Module_11$target_proteins
[1] "TET2"


$Module_12
$Module_12$module_id
[1] "RC4_1"

$Module_12$genes
 [1] "ANGEL1"   "C5ORF58"  "CMTR1"    "EIF2S1"   "EIF2S3"   "EIF3A"
 [7] "EIF3B"    "EIF3C"    "EIF3D"    "EIF3E"    "EIF3F"    "EIF3FP3"
[13] "EIF3G"    "EIF3H"    "EIF3I"    "EIF3K"    "EIF3L"    "EIF3M"
[19] "EIF4A2"   "EIF4B"    "EIF4E"    "EIF4E1B"  "EIF4E3"   "EIF4EBP1"
[25] "EIF4EBP2" "EIF4EBP3" "EIF4G1"   "EIF4G2"   "EIF4G3"   "EIF4H"
[31] "FAM188B"  "GSPT1"    "IGSF8"    "METAP2"   "OTUD6B"   "PHACTR3"
[37] "SLC8B1"   "SLFN14"   "ZNF746"   "IGKV2-28" "PTCHD4"   "FAM174B"
[43] "TMEM232"  "TAFA4"

$Module_12$size
[1] 44

$Module_12$algorithm
[1] "FASTGREEDY"

$Module_12$depth
[1] 4

$Module_12$target_proteins
[1] "EIF4E"


$Module_13
$Module_13$module_id
[1] "RC5_1"

$Module_13$genes
 [1] "ATG13"    "ATG4B"    "BUD23"    "DUX4"     "EIF1AD"   "GIN1"
 [7] "HBA1"     "HMGB1"    "KIAA1755" "LRRC47"   "N6AMT2"   "NDN"
[13] "RPLP0P6"  "RPS13"    "RPS14"    "RPS15A"   "RPS25"    "RPS3A"
[19] "RPS4X"    "RPS5"     "RPS8"     "WIBG"     "ZBTB1"

$Module_13$size
[1] 23

$Module_13$algorithm
[1] "FASTGREEDY"

$Module_13$depth
[1] 5

$Module_13$target_proteins
[1] "RPS25"


$Module_14
$Module_14$module_id
[1] "RC3_3"

$Module_14$genes
 [1] "ABCF1"       "BHLHA15"     "CEP250"      "DUSP5"       "ETF1"
 [6] "FBP1"        "GAGE12F"     "GAGE12G"     "GAGE13"      "GAGE2A"
[11] "IFRD1"       "IFRD2"       "IGHV1-45"    "IGHV1OR15-1" "PAN2"
[16] "PRAMEF11"    "PRAMEF14"    "RCHY1"       "RPS15"       "RPS17"
[21] "RPS18"       "RPS23"       "RPS26"       "RPS27A"      "RPS9"
[26] "TNFAIP8L1"   "TRIM31"      "HMGN1P30"    "RPL32P18"

$Module_14$size
[1] 29

$Module_14$algorithm
[1] "FASTGREEDY"

$Module_14$depth
[1] 3

$Module_14$target_proteins
[1] "RPS26"


$Module_15
$Module_15$module_id
[1] "RC5_1"

$Module_15$genes
 [1] "ACAD9"          "ANGEL2"         "ATP5D"          "ATP5J2-PTCD1"
 [5] "ATPAF1"         "C10ORF2"        "C1ORF123"       "C6ORF203"
 [9] "C7ORF55-LUC7L2" "CS"             "DHX30"          "ELAC2"
[13] "ERAL1"          "FASTKD2"        "FASTKD5"        "GRSF1"
[17] "GUF1"           "IBA57"          "ICT1"           "LYRM4"
[21] "METTL15"        "METTL17"        "MRPS36"         "MRRF"
[25] "MTERF1"         "MTERF3"         "MTIF3"          "MTPAP"
[29] "MTRF1"          "NFS1"           "PDK3"           "PMPCA"
[33] "PNPT1"          "POLRMT"         "RCC1L"          "RNMTL1"
[37] "RPUSD4"         "SLIRP"          "SUPV3L1"        "TFAM"
[41] "TRMT10C"        "TRUB2"          "MRRFP1"         "TRNI"

$Module_15$size
[1] 44

$Module_15$algorithm
[1] "FASTGREEDY"

$Module_15$depth
[1] 5

$Module_15$target_proteins
[1] "RPUSD4"  "TRMT10C" "TRUB2"


$Module_16
$Module_16$module_id
[1] "RC4_2"

$Module_16$genes
 [1] "AK4"          "AUH"          "C21ORF33"     "CDK5RAP1"     "CLPP"
 [6] "DHTKD1"       "EEF1AKMT3"    "FLAD1"        "GTPBP3"       "LYRM7"
[11] "MGME1"        "MRM1"         "MUT"          "OXLD1"        "PDK1"
[16] "POLG"         "PREPL"        "PUS1"         "SPRYD4"       "THG1L"
[21] "THNSL1"       "TRIT1"        "TRMT11"       "TRMT2B"       "TRMT5"
[26] "TRMT61B"      "TSFM"         "TWNK"         "LOC100507855"

$Module_16$size
[1] 29

$Module_16$algorithm
[1] "FASTGREEDY"

$Module_16$depth
[1] 4

$Module_16$target_proteins
[1] "PUS1"    "TRMT61B"


$Module_17
$Module_17$module_id
[1] "RC5_1"

$Module_17$genes
 [1] "C12ORF65"   "CZIB"       "GADD45GIP1" "GTPBP6"     "H1FNT"
 [6] "MIEF1-2"    "MRM2"       "MRPL1"      "MRPL10"     "MRPL14"
[11] "MRPL15"     "MRPL16"     "MRPL18"     "MRPL19"     "MRPL2"
[16] "MRPL20"     "MRPL22"     "MRPL23"     "MRPL27"     "MRPL28"
[21] "MRPL30"     "MRPL32"     "MRPL34"     "MRPL35"     "MRPL37"
[26] "MRPL38"     "MRPL39"     "MRPL40"     "MRPL42"     "MRPL44"
[31] "MRPL45"     "MRPL46"     "MRPL48"     "MRPL49"     "MRPL50"
[36] "MRPL51"     "MRPL52"     "MRPL53"     "MRPL54"     "MRPL55"
[41] "MRPL57"     "MRPL58"     "MRPS18A"    "MRPS30"     "MTERF4"
[46] "MTRES1"     "NGRN"       "NSUN4"      "RBMS3"      "TMEM177"

$Module_17$size
[1] 50

$Module_17$algorithm
[1] "FASTGREEDY"

$Module_17$depth
[1] 5

$Module_17$target_proteins
[1] "NSUN4"


$Module_18
$Module_18$module_id
[1] "RC5_2"

$Module_18$genes
 [1] "ASCC1"  "DDX28"  "GTPBP8" "MALSU1" "MRM3"   "MRPL11" "MRPL13" "MRPL17"
 [9] "MRPL21" "MRPL24" "MRPL3"  "MRPL43" "MRPL47" "MTG1"   "PUS10"  "PUS3"
[17] "PUS7"   "PUS7L"  "RPUSD1" "RPUSD2" "SOD2-2" "TSTD1"  "TSTD3"

$Module_18$size
[1] 23

$Module_18$algorithm
[1] "FASTGREEDY"

$Module_18$depth
[1] 5

$Module_18$target_proteins
[1] "PUS3" "PUS7"


$Module_19
$Module_19$module_id
[1] "RC5_1"

$Module_19$genes
 [1] "C2ORF78"   "CRNDE"     "FAIM3"     "HNRNPA2B1" "HNRNPA3"   "HNRNPH2"
 [7] "MATR3-2"   "MIR199A2"  "MIR200A"   "OR9Q2"

$Module_19$size
[1] 10

$Module_19$algorithm
[1] "FASTGREEDY"

$Module_19$depth
[1] 5

$Module_19$target_proteins
[1] "HNRNPA2B1"


$Module_20
$Module_20$module_id
[1] "RC5_2"

$Module_20$genes
 [1] "CXORF23"   "DDX3X"     "HOXC-AS3"  "IGF2BP3"   "KHDC4"     "LINC01232"
 [7] "MATR3"     "MIR122"    "MIR140"    "MIR16-1"   "MIR18B"    "MIR206"
[13] "MIR20A"    "MIR29B2"   "MIR451A"   "MIR92A1"   "PTBP1"     "PTBP3"
[19] "PUF60"     "YBX1"      "SNORD19B"  "ZMIZ1-AS1" "TMEM191B"

$Module_20$size
[1] 23

$Module_20$algorithm
[1] "FASTGREEDY"

$Module_20$depth
[1] 5

$Module_20$target_proteins
[1] "IGF2BP3" "YBX1"


$Module_21
$Module_21$module_id
[1] "RC5_3"

$Module_21$genes
 [1] "ADARB1"     "DANCR"      "DDX21"      "FGF11"      "HNRNPA1"
 [6] "LARP6"      "MIR1-2"     "MIR106A"    "MIR138-1"   "MIR141"
[11] "MIR145"     "MIR7-3"     "MIR9-3"     "NONO"       "RNASE1"
[16] "STRBP"      "YBX3"       "HNRNPA1P48" "HNRNPA1P70"

$Module_21$size
[1] 19

$Module_21$algorithm
[1] "FASTGREEDY"

$Module_21$depth
[1] 5

$Module_21$target_proteins
[1] "ADARB1"


$Module_22
$Module_22$module_id
[1] "RC5_1"

$Module_22$genes
 [1] "ADARB2"  "DHX36"   "L1TD1"   "LIN28A"  "LIN28B"  "MIR1-1"  "MIR106B"
 [8] "MIR19B1" "MIR205"  "MIR29C"  "MIR31"   "MIR34B"  "MIR7-1"  "MIR7-2"
[15] "PURA"    "PURB"    "SUGP2"   "TRA2A"   "U2SURP"  "YBX2"    "ZC3H8"
[22] "ZNF346"

$Module_22$size
[1] 22

$Module_22$algorithm
[1] "FASTGREEDY"

$Module_22$depth
[1] 5

$Module_22$target_proteins
[1] "ADARB2"


$Module_23
$Module_23$module_id
[1] "RC5_1"

$Module_23$genes
 [1] "ALG13"    "CCAT1"    "CSDE1"    "CTIF"     "DDX19B-2" "FUBP3"
 [7] "GLE1"     "IGF2BP2"  "LARP4"    "LARP4B"   "MKRN2"    "NUPL2"
[13] "PAIP2"    "PUM1"     "RBM47"    "ZCCHC3"   "ZCCHC24"

$Module_23$size
[1] 17

$Module_23$algorithm
[1] "FASTGREEDY"

$Module_23$depth
[1] 5

$Module_23$target_proteins
[1] "IGF2BP2"


$Module_24
$Module_24$module_id
[1] "RC5_1"

$Module_24$genes
 [1] "GRM2"        "ILF3"        "MAB21L2"     "MEIOC"       "RNU5A-1"
 [6] "RNU5B-1"     "SNORD3C"     "YTHDC2"      "RNU2-4P"     "SNORA34"
[11] "SNORA57"     "SNORA71D"    "SNORD116-18" "SNORD116-22" "SNORD116-24"
[16] "SNORD116-29" "SNORD19"     "SNORD50A"    "SNORD50B"    "SNORD88C"
[21] "SNORD95"

$Module_24$size
[1] 21

$Module_24$algorithm
[1] "FASTGREEDY"

$Module_24$depth
[1] 5

$Module_24$target_proteins
[1] "YTHDC2"


$Module_25
$Module_25$module_id
[1] "RC5_2"

$Module_25$genes
 [1] "BRD7"      "C14ORF166" "C2ORF49"   "CAND1"     "DDX1"      "FAM98A"
 [7] "FAM98B"    "FAM98C"    "LRRC16B"   "LSM12"     "RPL10AP3"  "RTCB"
[13] "RTRAF"     "UCP3"      "YTHDF2"    "ZBTB8OS"   "RPL30P8"   "MCRIP2"
[19] "MCRIP1"

$Module_25$size
[1] 19

$Module_25$algorithm
[1] "FASTGREEDY"

$Module_25$depth
[1] 5

$Module_25$target_proteins
[1] "YTHDF2"


$Module_26
$Module_26$module_id
[1] "RC5_1"

$Module_26$genes
 [1] "AGO1"    "AGO3"    "ANKHD1"  "ANKRD17" "HELZ"    "MEX3B"   "PAN3"
 [8] "RC3H1"   "RNF10"   "YTHDF3"  "ZC3H7A"  "ZCCHC2"

$Module_26$size
[1] 12

$Module_26$algorithm
[1] "FASTGREEDY"

$Module_26$depth
[1] 5

$Module_26$target_proteins
[1] "YTHDF3"


$Module_27
$Module_27$module_id
[1] "RC5_2"

$Module_27$genes
 [1] "BICC1"        "CELF1"        "CELF2"        "CPEB4"        "DAZL"
 [6] "DCAF4"        "EIF4ENIF1"    "ELAVL3"       "FAM120C"      "FAM195A"
[11] "FAM195B"      "IGF2BP1"      "MBNL2"        "MEX3D"        "OTUD4"
[16] "PRRC2B"       "R3HDM1"       "R3HDM2"       "RBMS1"        "YTHDF1"
[21] "ZCCHC11"      "DFNB59"       "LOC100506797"

$Module_27$size
[1] 23

$Module_27$algorithm
[1] "FASTGREEDY"

$Module_27$depth
[1] 5

$Module_27$target_proteins
[1] "IGF2BP1" "YTHDF1"


$Module_28
$Module_28$module_id
[1] "RC4_1"

$Module_28$genes
[1] "FOXA1"     "MROH8"     "NSUN2"     "NSUN5"     "TSPYL5"    "ZFP91"
[7] "ZNF653"    "LOC113230"

$Module_28$size
[1] 8

$Module_28$algorithm
[1] "FASTGREEDY"

$Module_28$depth
[1] 4

$Module_28$target_proteins
[1] "NSUN2" "NSUN5"


$Module_29
$Module_29$module_id
[1] "RC3_2"

$Module_29$genes
 [1] "ADAR"       "ARHGEF10L"  "C5ORF42"    "C8ORF88"    "CCDC178"
 [6] "CDKN2AIPNL" "DDX17"      "DHX33"      "DHX9"       "DNAJC9"
[11] "DROSHA"     "DTHD1"      "DUS2"       "HECTD1"     "HNRNPU"
[16] "HNRNPUL1"   "IFI16"      "IGHMBP2"    "LAS1L"      "MTF1"
[21] "NKRF"       "NOL9"       "OR13D1"     "OR5AR1"     "PCBP2-OT1"
[26] "PCDHA2"     "PROB1"      "PRSS41"     "RHOBTB1"    "RNF2"
[31] "RNU6-1"     "RO60"       "SART3"      "SCAF8"      "SND1"
[36] "SSB"        "TRAJ56"     "TRIM26"     "XRN2"       "YLPM1"
[41] "LINC00173"  "LINC01016"  "OR6C3"      "RNF222"

$Module_29$size
[1] 44

$Module_29$algorithm
[1] "FASTGREEDY"

$Module_29$depth
[1] 3

$Module_29$target_proteins
[1] "ADAR"


$Module_30
$Module_30$module_id
[1] "RC5_1"

$Module_30$genes
 [1] "ADAMTS16" "ANKRD50"  "ARHGAP26" "C1ORF35"  "CDK9"     "CPSF7"
 [7] "DDX42"    "FAM76A"   "FAM76B"   "MAPKAPK2" "MECP2"    "NSRP1"
[13] "PPIL4"    "PPP1R10"  "PRPF40A"  "PRPF4B"   "RBM15B"   "RBM25"
[19] "SLC35G3"  "SUV420H2" "TOP1"     "TOX4"     "WDR82"    "MROH7"

$Module_30$size
[1] 24

$Module_30$algorithm
[1] "FASTGREEDY"

$Module_30$depth
[1] 5

$Module_30$target_proteins
[1] "RBM15B"


$Module_31
$Module_31$module_id
[1] "RC5_1"

$Module_31$genes
 [1] "ACIN1"    "AKAP17A"  "ALYREF"   "ANO7"     "API5"     "C11ORF57"
 [7] "C17ORF85" "C19ORF47" "CABP7"    "CCDC9"    "CHTOP"    "DDX39B"
[13] "DHX34"    "EIF4A3"   "FYTTD1"   "LUZP4"    "MAGOH"    "MYCN"
[19] "NCBP3"    "PNN"      "POLDIP3"  "PYM1"     "RBM33"    "RECQL"
[25] "SARNP"    "THOC1"    "THOC2"    "THOC3"    "THOC5"    "THOC6"
[31] "THOC7"    "UPF2"     "UPF3A"    "UPF3B"    "ZC3H11A"  "ZC3H14"
[37] "HILS1"    "MAGOH2P"  "OR6S1"

$Module_31$size
[1] 39

$Module_31$algorithm
[1] "FASTGREEDY"

$Module_31$depth
[1] 5

$Module_31$target_proteins
[1] "ALYREF"


$Module_32
$Module_32$module_id
[1] "RC5_2"

$Module_32$genes
 [1] "ALKBH1"       "ALKBH5"       "ANLN"         "CBLL1"        "CBLL2"
 [6] "EEF1AKNMT"    "GUSBP4"       "HNRNPC"       "LINC00339"    "LINC00847"
[11] "LINC01268"    "LOC100129917" "LOC100287015" "LOC728743"    "METTL14"
[16] "METTL16"      "METTL4"       "METTL5"       "NNT-AS1"      "PSMA3-AS1"
[21] "RBM15"        "RBMX"         "SH3BP5-AS1"   "TTN-AS1"      "VIRMA"
[26] "WTAP"         "YTHDC1"       "ZC3H13"       "ZCCHC4"       "ZFP69"

$Module_32$size
[1] 30

$Module_32$algorithm
[1] "FASTGREEDY"

$Module_32$depth
[1] 5

$Module_32$target_proteins
[1] "ALKBH1"  "ALKBH5"  "METTL14" "RBM15"   "VIRMA"   "WTAP"    "YTHDC1"
[8] "ZC3H13"


$Module_33
$Module_33$module_id
[1] "RC3_1"

$Module_33$genes
 [1] "ASCL5"    "C10ORF11" "CALY"     "CASQ2"    "CCDC81"   "CPNE4"
 [7] "DKC1"     "EFCAB12"  "EFCAB5"   "FTSJ3"    "GLI4"     "GZF1"
[13] "H2AFB3"   "HBP1"     "HIST1H1B" "HIST1H1C" "HIST1H1D" "HIST1H1T"
[19] "HP1BP3"   "KIAA0020" "PNMAL1"   "PPAN"     "PRDM10"   "PRDM5"
[25] "RBM19"    "REXO4"    "SLCO6A1"  "SNORA73B" "SURF2"    "ZBTB47"
[31] "ZBTB48"   "ZCCHC9"   "ZNF22"    "ZNF317"   "ZNF616"   "ZNF646"
[37] "ZNF70"    "ZNF71"    "ZNF777"   "ZSCAN25"  "TAAR3"    "ZSCAN5B"

$Module_33$size
[1] 42

$Module_33$algorithm
[1] "FASTGREEDY"

$Module_33$depth
[1] 3

$Module_33$target_proteins
[1] "DKC1"


$Module_34
$Module_34$module_id
[1] "RC4_1"

$Module_34$genes
 [1] "BCCIP"    "BRIX1"    "DIMT1"    "EBNA1BP2" "ESF1"     "FAM207A"
 [7] "GNL1"     "GNL2"     "GNL3"     "GNL3L"    "GRWD1"    "KCTD19"
[13] "KRR1"     "LTV1"     "MAFB"     "MAK16"    "NIFK"     "NIP7"
[19] "NOB1"     "POLR1E"   "PSKH1"    "PWP1"     "RPF1"     "RRP1"
[25] "RRP12"    "RRP15"    "RRP1B"    "SDAD1"    "TRMT112"  "TRMT61A"
[31] "TSR1"     "TSR2"     "TWISTNB"  "WDR17"    "TRMT9B"

$Module_34$size
[1] 35

$Module_34$algorithm
[1] "FASTGREEDY"

$Module_34$depth
[1] 4

$Module_34$target_proteins
[1] "TRMT61A"


$Module_35
$Module_35$module_id
[1] "RC4_2"

$Module_35$genes
 [1] "ARHGAP40" "BOP1"     "CDKL2"    "DDX10"    "DDX18"    "DDX47"
 [7] "DDX52"    "DDX55"    "DDX56"    "METTL1"   "NAT10"    "NOC3L"
[13] "NOP9"     "PES1"     "PUM3"     "RPF2"     "SLC9B2"   "TRMT6"
[19] "TRUB1"    "WDR12"    "WDR18"    "WDR74"

$Module_35$size
[1] 22

$Module_35$algorithm
[1] "FASTGREEDY"

$Module_35$depth
[1] 4

$Module_35$target_proteins
[1] "METTL1" "TRMT6"  "TRUB1"


$Module_36
$Module_36$module_id
[1] "RC4_3"

$Module_36$genes
[1] "DDX24"  "NSUN6"  "NSUN7"  "TRDMT1" "UTP14A"

$Module_36$size
[1] 5

$Module_36$algorithm
[1] "FASTGREEDY"

$Module_36$depth
[1] 4

$Module_36$target_proteins
[1] "NSUN6" "NSUN7"

In [3]:
sample_condition <- pheno_data %>%
    dplyr::select(`disease state:ch1`) %>%
    dplyr::mutate(condition = ifelse(`disease state:ch1` == "septic shock patient", "case", "control"))
sample_condition_list <- sample_condition$condition
names(sample_condition_list) <- rownames(sample_condition)
sample_condition_list

GSM647527 GSM647528 GSM647529 GSM647530 GSM647531 GSM647532 GSM647533 GSM647534
   "case"    "case"    "case"    "case"    "case"    "case" "control" "control"
GSM647535 GSM647536 GSM647537 GSM647538 GSM647539 GSM647540 GSM647541 GSM647542
   "case" "control" "control" "control" "control"    "case"    "case"    "case"
GSM647543 GSM647544 GSM647545 GSM647546 GSM647547 GSM647548 GSM647549 GSM647550
   "case"    "case"    "case"    "case"    "case"    "case"    "case"    "case"
GSM647551 GSM647552 GSM647553 GSM647554 GSM647555 GSM647556 GSM647557 GSM647558
   "case"    "case"    "case"    "case"    "case"    "case"    "case"    "case"
GSM647559 GSM647560 GSM647561 GSM647562 GSM647563 GSM647564 GSM647565 GSM647566
   "case"    "case"    "case"    "case"    "case"    "case"    "case" "control"
GSM647567 GSM647568 GSM647569 GSM647570 GSM647571 GSM647572 GSM647573 GSM647574
   "case"    "case"    "case"    "case"    "case"    "case"    "case"    "case"
GSM647575 GSM647576 GSM647577 GSM647578 GSM647579 GSM647580 GSM647581 GSM647582
"control"    "case"    "case"    "case"    "case"    "case"    "case"    "case"
GSM647583 GSM647584 GSM647585 GSM647586 GSM647587 GSM647588 GSM647589 GSM647590
   "case"    "case"    "case"    "case"    "case"    "case" "control" "control"
GSM647591 GSM647592 GSM647593 GSM647594 GSM647595 GSM647596 GSM647597 GSM647598
   "case"    "case"    "case"    "case"    "case"    "case"    "case"    "case"
GSM647599 GSM647600 GSM647601 GSM647602 GSM647603 GSM647604 GSM647605 GSM647606
   "case"    "case"    "case"    "case"    "case" "control" "control" "control"
GSM647607 GSM647608 GSM647609 GSM647610 GSM647611 GSM647612 GSM647613 GSM647614
"control" "control"    "case"    "case"    "case"    "case"    "case"    "case"
GSM647615 GSM647616 GSM647617 GSM647618 GSM647619 GSM647620 GSM647621 GSM647622
   "case"    "case"    "case"    "case"    "case"    "case" "control" "control"
GSM647623 GSM647624 GSM647625 GSM647626 GSM647627 GSM647628 GSM647629
"control" "control" "control" "control"    "case"    "case"    "case"

In [4]:
module_genes <- lapply(modules, function(module) {
  intersect(module$genes, rownames(exp_data))
})

# Remove empty modules and modules with too few genes
min_genes <- 3
module_genes <- module_genes[sapply(module_genes, length) >= min_genes]

In [ ]:
results <- final_integrated_analysis(exp_data, sample_condition_list, modules)

Starting integrated analysis...

Input genes: 20848

Input samples: 103

Valid modules: 34

Case samples: 82

Control samples: 21


Running intra-module analysis...

Intra-module analysis completed: 7334 gene pairs


Running inter-module analysis...

In [ ]:
names(results)

[1] "intra_module_results"    "inter_module_results"
[3] "module_activity_results" "summary"
[5] "metadata"

In [ ]:
results$summary

$overall_summary
    analysis_type total_pairs significant_pairs
1    intra-module        7881              3077
2    inter-module      225022             88819
3 module-activity           0                 0

$input_parameters
$input_parameters$total_genes
[1] 20848

$input_parameters$total_samples
[1] 103

$input_parameters$case_samples
[1] 82

$input_parameters$control_samples
[1] 21

$input_parameters$valid_modules
[1] 36

$input_parameters$analysis_methods
[1] "gsva"   "ssgsea" "zscore" "plage"

In [ ]:
results$intra_module_results %>% arrange(odds_ratio)

               activity_method event1   event2   event_name p_value
odds ratio1699 Intra-Module    ATL2     CYSTM1   Module_6   2.811523e-14
odds ratio1716 Intra-Module    C5AR2    CYSTM1   Module_6   4.021482e-12
odds ratio4990 Intra-Module    THOC1    THOC7    Module_15  8.136361e-14
odds ratio893  Intra-Module    RPA1     UROD     Module_3   2.348680e-11
odds ratio2742 Intra-Module    ATPAF1   MRPS36   Module_9   2.348680e-11
odds ratio4129 Intra-Module    EIF3L    EIF4EBP1 Module_13  2.348680e-11
odds ratio747  Intra-Module    NT5DC1   TP53I3   Module_3   2.441811e-10
odds ratio846  Intra-Module    PITPNA   TP53I3   Module_3   2.441811e-10
odds ratio1953 Intra-Module    LYRM7    OXLD1    Module_7   2.441811e-10
odds ratio1954 Intra-Module    LYRM7    PDK1     Module_7   2.441811e-10
odds ratio7629 Intra-Module    PUM2     RBM47    Module_32  1.542924e-13
odds ratio3471 Intra-Module    RPL36    RPP38    Module_11  2.270715e-09
odds ratio1319 Intra-Module    GNPDA2   RMDN1    Module_4   4.764011e-13
odds ratio859  Intra-Module    PITPNB   TP53I3   Module_3   1.582724e-11
odds ratio1804 Intra-Module    CDK5RAP1 COX8A    Module_7   1.582724e-11
odds ratio1708 Intra-Module    ATL3     CYSTM1   Module_6   7.417998e-12
odds ratio4112 Intra-Module    EIF3K    EIF4EBP1 Module_13  7.417998e-12
odds ratio7615 Intra-Module    PRRC2B   RBMS1    Module_32  7.417998e-12
odds ratio817  Intra-Module    PANK4    TP53I3   Module_3   1.739602e-10
odds ratio4034 Intra-Module    EIF3F    EIF4EBP1 Module_13  1.739602e-10
odds ratio2690 Intra-Module    AFG3L2   TACO1    Module_9   2.642689e-12
odds ratio1965 Intra-Module    LYRM7    UQCC1    Module_7   1.467782e-07
odds ratio6583 Intra-Module    TRUB1    WDR12    Module_23  9.727968e-12
odds ratio4988 Intra-Module    THOC1    THOC5    Module_15  1.345107e-11
odds ratio6769 Intra-Module    NONO     PTBP3    Module_26  8.876453e-11
odds ratio271  Intra-Module    BDH2     TP53I3   Module_3   1.678694e-09
odds ratio6152 Intra-Module    DDX24    DDX31    Module_22  1.678694e-09
odds ratio7623 Intra-Module    PUM1     RBMS1    Module_32  1.678694e-09
odds ratio7635 Intra-Module    R3HDM2   RBM47    Module_32  1.089939e-11
odds ratio1966 Intra-Module    LYRM7    UQCC2    Module_7   1.917250e-09
⋮              ⋮               ⋮        ⋮        ⋮          ⋮
odds ratio551  Intra-Module    LYPLA2   RPA1     Module_3   3.501772e-11
odds ratio1085 Intra-Module    FPGT     GNPDA2   Module_4   3.574956e-11
odds ratio3586 Intra-Module    ENY2     RPS6     Module_12  1.089939e-11
odds ratio7648 Intra-Module    RBM47    ZCCHC11  Module_32  1.089939e-11
odds ratio1870 Intra-Module    COX8A    UQCC1    Module_7   1.678694e-09
odds ratio5168 Intra-Module    NSRP1    WDR82    Module_17  1.678694e-09
odds ratio1711 Intra-Module    ATL3     NSUN3    Module_6   8.876453e-11
odds ratio4660 Intra-Module    MRPL28   TMEM177  Module_14  8.876453e-11
odds ratio5255 Intra-Module    ANAPC15  ZNF677   Module_18  8.876453e-11
odds ratio1553 Intra-Module    RMDN1    TGDS     Module_4   1.584607e-11
odds ratio821  Intra-Module    PIN4     PITPNB   Module_3   1.739602e-10
odds ratio1709 Intra-Module    ATL3     LPAR4    Module_6   1.739602e-10
odds ratio5145 Intra-Module    FAM76B   WDR82    Module_17  8.598217e-08
odds ratio4980 Intra-Module    SARNP    THOC1    Module_15  1.582724e-11
odds ratio824  Intra-Module    PIN4     RPA1     Module_3   2.270715e-09
odds ratio1854 Intra-Module    COX8A    LYRM7    Module_7   2.270715e-09
odds ratio7495 Intra-Module    CELF2    R3HDM2   Module_32  9.926832e-12
odds ratio1832 Intra-Module    CLPP     LYRM7    Module_7   2.441811e-10
odds ratio1725 Intra-Module    CYSTM1   LPAR6    Module_6   1.075608e-10
odds ratio1947 Intra-Module    LYPLAL1  TRMT61B  Module_7   1.828096e-13
odds ratio5615 Intra-Module    PSENEN   ZNF677   Module_18  5.745997e-14
odds ratio4986 Intra-Module    SARNP    UPF3A    Module_15  1.990605e-12
odds ratio1556 Intra-Module    RMDN1    UAP1     Module_4   1.153803e-12
odds ratio1714 Intra-Module    ATL3     TAMM41   Module_6   2.811523e-14
odds ratio1724 Intra-Module    CYSTM1   LPAR4    Module_6   2.811523e-14
odds ratio1726 Intra-Module    CYSTM1   NSUN3    Module_6   2.811523e-14
odds ratio1727 Intra-Module    CYSTM1   SLC2A12  Module_6   2.811523e-14
odds ratio1728 Intra-Module    CYSTM1   SLC7A13  Module_6   2.811523e-14
odds ratio1729 Intra-Module    CYSTM1   TAMM41   Module_6   2.811523e-14
odds ratio1730 Intra-Module    CYSTM1   TM4SF5   Module_6   4.021482e-12
               odds_ratio  case_pattern_ratio control_pattern_ratio
odds ratio1699 0.000000000 0.00000000         0.7142857
odds ratio1716 0.000000000 0.00000000         0.6666667
odds ratio4990 0.006845255 0.02439024         0.8095238
odds ratio893  0.006887415 0.01219512         0.6666667
odds ratio2742 0.006887415 0.01219512         0.6666667
odds ratio4129 0.006887415 0.01219512         0.6666667
odds ratio747  0.008372504 0.01219512         0.6190476
odds ratio846  0.008372504 0.01219512         0.6190476
odds ratio1953 0.008372504 0.01219512         0.6190476
odds ratio1954 0.008372504 0.01219512         0.6190476
odds ratio7629 0.009730273 0.04878049         0.8571429
odds ratio3471 0.010101293 0.01219512         0.5714286
odds ratio1319 0.010827599 0.08536585         0.9047619
odds ratio859  0.011182507 0.02439024         0.7142857
odds ratio1804 0.011182507 0.02439024         0.7142857
odds ratio1708 0.013205968 0.03658537         0.7619048
odds ratio4112 0.013205968 0.03658537         0.7619048
odds ratio7615 0.013205968 0.03658537         0.7619048
odds ratio817  0.013727361 0.02439024         0.6666667
odds ratio4034 0.013727361 0.02439024         0.6666667
odds ratio2690 0.014482375 0.07317073         0.8571429
odds ratio1965 0.014583954 0.01219512         0.4761905
odds ratio6583 0.015324744 0.07317073         0.8095238
odds ratio4988 0.015730882 0.12195122         0.9047619
odds ratio6769 0.016686281 0.03658537         0.7142857
odds ratio271  0.016726822 0.02439024         0.6190476
odds ratio6152 0.016726822 0.02439024         0.6190476
odds ratio7623 0.016726822 0.02439024         0.6190476
odds ratio7635 0.016773329 0.06097561         0.8095238
odds ratio1966 0.016937967 0.02439024         0.6190476
⋮              ⋮           ⋮                  ⋮
odds ratio551   56.87596   0.9512195          0.23809524
odds ratio1085  57.32751   0.8658537          0.09523810
odds ratio3586  59.61846   0.9390244          0.19047619
odds ratio7648  59.61846   0.9390244          0.19047619
odds ratio1870  59.78422   0.9756098          0.38095238
odds ratio5168  59.78422   0.9756098          0.38095238
odds ratio1711  59.92947   0.9634146          0.28571429
odds ratio4660  59.92947   0.9634146          0.28571429
odds ratio5255  59.92947   0.9634146          0.28571429
odds ratio1553  67.38528   0.8902439          0.09523810
odds ratio821   72.84721   0.9756098          0.33333333
odds ratio1709  72.84721   0.9756098          0.33333333
odds ratio5145  74.95669   0.9878049          0.47619048
odds ratio4980  89.42538   0.9756098          0.28571429
odds ratio824   98.99723   0.9878049          0.42857143
odds ratio1854  98.99723   0.9878049          0.42857143
odds ratio7495  99.46628   0.8414634          0.04761905
odds ratio1832 119.43859   0.9878049          0.38095238
odds ratio1725 134.93957   0.9878049          0.33333333
odds ratio1947 148.15782   0.8902439          0.04761905
odds ratio5615 167.30984   0.9024390          0.04761905
odds ratio4986 178.02776   0.9878049          0.28571429
odds ratio1556       Inf   0.8048780          0.00000000
odds ratio1714       Inf   1.0000000          0.28571429
odds ratio1724       Inf   1.0000000          0.23809524
odds ratio1726       Inf   1.0000000          0.23809524
odds ratio1727       Inf   1.0000000          0.23809524
odds ratio1728       Inf   1.0000000          0.28571429
odds ratio1729       Inf   1.0000000          0.23809524
odds ratio1730       Inf   1.0000000          0.33333333
               case_correlation control_correlation correlation_change
odds ratio1699  0.162747589     -0.193127068         0.355874656
odds ratio1716  0.528467903      0.476991103         0.051476800
odds ratio4990  0.596738605      0.877669432        -0.280930827
odds ratio893   0.348851184      0.241993597         0.106857587
odds ratio2742  0.680968401      0.606499294         0.074469107
odds ratio4129  0.525697906      0.079682944         0.446014962
odds ratio747   0.130941434      0.163026459        -0.032085025
odds ratio846   0.248828352      0.336091418        -0.087263065
odds ratio1953  0.480857292      0.287911433         0.192945859
odds ratio1954 -0.059417098      0.432108289        -0.491525387
odds ratio7629  0.754519399      0.417626476         0.336892923
odds ratio3471  0.753379221      0.407962788         0.345416433
odds ratio1319  0.136071876      0.800554837        -0.664482961
odds ratio859   0.004146153     -0.254566332         0.258712484
odds ratio1804  0.185881366     -0.004365506         0.190246872
odds ratio1708  0.489807275      0.358199844         0.131607431
odds ratio4112  0.704518380      0.434161592         0.270356788
odds ratio7615 -0.226531085      0.463246232        -0.689777316
odds ratio817   0.023117525      0.011894358         0.011223168
odds ratio4034  0.458599900      0.152839777         0.305760122
odds ratio2690  0.513668027     -0.019941105         0.533609132
odds ratio1965  0.729522264      0.680521566         0.049000698
odds ratio6583  0.834472691      0.889634413        -0.055161722
odds ratio4988 -0.363085098     -0.033862095        -0.329223003
odds ratio6769 -0.098761112      0.315808927        -0.414570039
odds ratio271  -0.162695304      0.075176648        -0.237871952
odds ratio6152 -0.088884011     -0.079106349        -0.009777662
odds ratio7623  0.320902105      0.459510187        -0.138608082
odds ratio7635  0.496592504      0.439643047         0.056949457
odds ratio1966 -0.302689293     -0.545802740         0.243113446
⋮              ⋮                ⋮                   ⋮
odds ratio551  -0.36752949      -0.090602473        -0.27692702
odds ratio1085  0.45459160       0.831095666        -0.37650407
odds ratio3586  0.29833246       0.731616171        -0.43328372
odds ratio7648  0.51724738       0.320051209         0.19719618
odds ratio1870  0.15709262       0.173782924        -0.01669030
odds ratio5168  0.56619928       0.508597049         0.05760223
odds ratio1711 -0.13618253      -0.122994479        -0.01318805
odds ratio4660  0.02430588      -0.197324177         0.22163005
odds ratio5255 -0.09676415      -0.393507276         0.29674313
odds ratio1553  0.42050602       0.708896207        -0.28839019
odds ratio821   0.10336951       0.065223838         0.03814567
odds ratio1709  0.02852323      -0.156532569         0.18505580
odds ratio5145  0.61845968       0.642386611        -0.02392693
odds ratio4980  0.56251454       0.628415761        -0.06590122
odds ratio824   0.02225866       0.009114905         0.01314375
odds ratio1854 -0.02359386      -0.143738546         0.12014469
odds ratio7495  0.51035165       0.758687642        -0.24833599
odds ratio1832  0.40606558      -0.217416501         0.62348208
odds ratio1725 -0.03078481       0.057438271        -0.08822308
odds ratio1947  0.43381709       0.797585776        -0.36376869
odds ratio5615 -0.07900294       0.773723803        -0.85272674
odds ratio4986  0.68824429       0.635729807         0.05251448
odds ratio1556  0.46408847       0.863303260        -0.39921479
odds ratio1714  0.02477660       0.091077159        -0.06630056
odds ratio1724  0.02177660      -0.055077109         0.07685371
odds ratio1726 -0.09837172       0.101749208        -0.20012093
odds ratio1727 -0.01042994       0.259949764        -0.27037970
odds ratio1728  0.04213345       0.085993808        -0.04386036
odds ratio1729 -0.44831698      -0.430917589        -0.01739939
odds ratio1730  0.01510184       0.443027447        -0.42792561
               event1_effect_size event2_effect_size event_interaction
odds ratio1699  0.1859785          3.03624707         0.56467672
odds ratio1716  0.2516770          3.03624707         0.76415352
odds ratio4990 -0.7566848          0.30484696        -0.23067307
odds ratio893  -0.8977931          0.51902945        -0.46598106
odds ratio2742 -0.4998793          0.42687392        -0.21338545
odds ratio4129 -0.8598479          0.33174870        -0.28525344
odds ratio747  -0.7695806          1.43292874        -1.10275409
odds ratio846  -0.2404892          1.43292874        -0.34460393
odds ratio1953 -1.1615586         -0.03490773         0.04054738
odds ratio1954 -1.1615586          0.18924087        -0.21981436
odds ratio7629 -0.2052909          1.38282760        -0.28388195
odds ratio3471 -0.7714472         -0.06244535         0.04817329
odds ratio1319 -0.8675646          0.91204151        -0.79125490
odds ratio859  -0.3729086          1.43292874        -0.53435145
odds ratio1804 -0.3859278          0.59828583        -0.23089512
odds ratio1708  1.2256841          3.03624707         3.72147974
odds ratio4112 -0.3964879          0.33174870        -0.13153435
odds ratio7615 -0.5502890          0.77377808        -0.42580159
odds ratio817  -0.4550329          1.43292874        -0.65202969
odds ratio4034 -0.8213419          0.33174870        -0.27247910
odds ratio2690 -0.8403166          0.22690269        -0.19067009
odds ratio1965 -1.1615586         -0.47652681         0.55351384
odds ratio6583 -1.0069103         -0.06102161         0.06144328
odds ratio4988 -0.7566848          0.74111814        -0.56079286
odds ratio6769 -0.6377336          0.78248432        -0.49901653
odds ratio271  -0.5384232          1.43292874        -0.77152205
odds ratio6152 -0.8492281          0.01477462        -0.01254702
odds ratio7623 -0.1311459          0.77377808        -0.10147780
odds ratio7635 -0.4077318          1.38282760        -0.56382273
odds ratio1966 -1.1615586          0.07673727        -0.08913484
⋮              ⋮                  ⋮                  ⋮
odds ratio551  0.13861301         -0.89779311        -0.12444581
odds ratio1085 0.60147143         -0.86756457        -0.52181530
odds ratio3586 0.90339897         -0.57793013        -0.52210148
odds ratio7648 1.38282760         -0.34687995        -0.47967517
odds ratio1870 0.59828583         -0.47652681        -0.28509924
odds ratio5168 0.11121196         -0.60518503        -0.06730381
odds ratio1711 1.22568410          0.09620222         0.11791353
odds ratio4660 0.58669907         -0.59673188        -0.35010204
odds ratio5255 0.58564821         -0.94046895        -0.55078396
odds ratio1553 0.91204151         -0.34108121        -0.31108022
odds ratio821  0.45325635         -0.37290860        -0.16902319
odds ratio1709 1.22568410         -0.06962054        -0.08533278
odds ratio5145 0.11112168         -0.60518503        -0.06724918
odds ratio4980 0.91920116         -0.75668483        -0.69554558
odds ratio824  0.45325635         -0.89779311        -0.40693043
odds ratio1854 0.59828583         -1.16155865        -0.69494408
odds ratio7495 0.58246708         -0.40773176        -0.23749033
odds ratio1832 0.09992106         -1.16155865        -0.11606418
odds ratio1725 3.03624707         -0.06443034        -0.19562643
odds ratio1947 0.19483648         -1.12732335        -0.21964371
odds ratio5615 0.96489760         -0.94046895        -0.90745624
odds ratio4986 0.91920116         -0.71289281        -0.65529190
odds ratio1556 0.91204151         -0.56068998        -0.51137253
odds ratio1714 1.22568410         -0.31491709        -0.38598887
odds ratio1724 3.03624707         -0.06962054        -0.21138515
odds ratio1726 3.03624707          0.09620222         0.29209371
odds ratio1727 3.03624707         -0.06036986        -0.18329780
odds ratio1728 3.03624707         -0.09170370        -0.27843509
odds ratio1729 3.03624707         -0.31491709        -0.95616610
odds ratio1730 3.03624707          0.10466727         0.31779568
               adj_p_value  significant
odds ratio1699 3.165373e-11 TRUE
odds ratio1716 1.864312e-09 TRUE
odds ratio4990 7.124740e-11 TRUE
odds ratio893  5.609076e-09 TRUE
odds ratio2742 5.609076e-09 TRUE
odds ratio4129 5.609076e-09 TRUE
odds ratio747  3.261680e-08 TRUE
odds ratio846  3.261680e-08 TRUE
odds ratio1953 3.261680e-08 TRUE
odds ratio1954 3.261680e-08 TRUE
odds ratio7629 1.215978e-10 TRUE
odds ratio3471 1.720722e-07 TRUE
odds ratio1319 3.128764e-10 TRUE
odds ratio859  4.162764e-09 TRUE
odds ratio1804 4.162764e-09 TRUE
odds ratio1708 2.923062e-09 TRUE
odds ratio4112 2.923062e-09 TRUE
odds ratio7615 2.923062e-09 TRUE
odds ratio817  2.636501e-08 TRUE
odds ratio4034 2.636501e-08 TRUE
odds ratio2690 1.388469e-09 TRUE
odds ratio1965 4.252790e-06 TRUE
odds ratio6583 3.435924e-09 TRUE
odds ratio4988 4.077225e-09 TRUE
odds ratio6769 1.706228e-08 TRUE
odds ratio271  1.322979e-07 TRUE
odds ratio6152 1.322979e-07 TRUE
odds ratio7623 1.322979e-07 TRUE
odds ratio7635 3.435924e-09 TRUE
odds ratio1966 1.496024e-07 TRUE
⋮              ⋮            ⋮
odds ratio551  7.826174e-09 TRUE
odds ratio1085 7.826174e-09 TRUE
odds ratio3586 3.435924e-09 TRUE
odds ratio7648 3.435924e-09 TRUE
odds ratio1870 1.322979e-07 TRUE
odds ratio5168 1.322979e-07 TRUE
odds ratio1711 1.706228e-08 TRUE
odds ratio4660 1.706228e-08 TRUE
odds ratio5255 1.706228e-08 TRUE
odds ratio1553 4.162764e-09 TRUE
odds ratio821  2.636501e-08 TRUE
odds ratio1709 2.636501e-08 TRUE
odds ratio5145 2.946198e-06 TRUE
odds ratio4980 4.162764e-09 TRUE
odds ratio824  1.720722e-07 TRUE
odds ratio1854 1.720722e-07 TRUE
odds ratio7495 3.435924e-09 TRUE
odds ratio1832 3.261680e-08 TRUE
odds ratio1725 2.018302e-08 TRUE
odds ratio1947 1.309747e-10 TRUE
odds ratio5615 5.660525e-11 TRUE
odds ratio4986 1.120568e-09 TRUE
odds ratio1556 6.994709e-10 TRUE
odds ratio1714 3.165373e-11 TRUE
odds ratio1724 3.165373e-11 TRUE
odds ratio1726 3.165373e-11 TRUE
odds ratio1727 3.165373e-11 TRUE
odds ratio1728 3.165373e-11 TRUE
odds ratio1729 3.165373e-11 TRUE
odds ratio1730 1.864312e-09 TRUE

In [ ]:
results$module_activity_results %>%
    group_by(activity_method) %>%
    summarise(n = n())

ERROR: Error in `group_by()`:
! Must group by variables found in `.data`.
✖ Column `activity_method` is not found.